### ISSUE TITLE
几个新问题

### ISSUE THREAD

**Issue by dzzxjl** [wanoyume/website-cn#1]
不懂node js，有两个小问题：
1. 网站加载速度过慢，无论是打开页面还是网页内评论或跳转等，有没有办法优化？
2. markdown那块编辑时好像有些问题

**Comment by tsq** [comment]
1. 网站速度慢，套用导演的一句话 `没钱`:joy: 服务器处理器和网络带宽都是最低配的。
2. markdown确实有问题，我也发现了。 我会跟进 nodeclub 有没有补丁更新

**Comment by dzzxjl** [comment]
@tsq 
我用的阿里云的学生低配，1核2G内存1M带宽，自己搭的一个小站点，感觉速度也不是很慢，web这块我也不是很懂🤣，机器国外的？

**Comment by tsq** [comment]
目前服务器是阿里云，位于华北石家庄，用的是1G内存+1M带宽。 

仔细调查了，加载速度慢还有一个重要原因是静态资源的加载，如js、css、img等，而这些资源现在走的都是阿里云的cdn，但效果貌似并不理想。

目前可做的一个优化是，对所有出现图片资源的地方加上阿里云oss的`图片优化querystring`。有时间的话我会把它一一补上。

**Comment by dzzxjl** [comment]
get
